# Docker-Compose version
version: '3.7'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: /usr/local/bin/gunicorn mycoll_project.wsgi:application -w 2 -b :443 --certfile=./certs/104.248.238.221/cert.pem  --keyfile=./certs/104.248.238.221/key.pem
    volumes:
      - .:/code
    ports:
      - 443
    depends_on:
    - db

  db:
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data: