version: '3.7'

services:
  web:
    build: .
    command: gunicorn mycoll_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
    - db

  db:
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data: