version: '3.7'

services:
  web:
    build: .
    command: gunicorn mycoll_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    networks:
      - webnet
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./certs:/etc/nginx/ssl
    ports:
      # Change the port on the left if you want to go back to PORT 8000
      - "80:80"
    networks:
      - webnet
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on: 
      - web

  db:
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: postgres
    networks:
      - webnet
    volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  webnet: